#+TITLE: jake.isnt.online

This is the index of my personal website found [[https://jake.isnt.online][here]].
It can be thought of as a projection of my wiki and github repos!
100% score on the [[https://www.foo.software/lighthouse][Lighthouse audit]].

* Goals
- Personal landing page with links
- No external resources loaded
- SEO Optimized
- Ten packets (to load instantly)

* Running
Dependencies are managed with Nix. Install `nix` and `direnv`. Open the folder in your system of choice, and all dependencies will install.

The flake has a few commands:

Hot reloading: `watch`
Build site: `build`
Deploy site: `deploy`

These commands may not be extensible enough to fit your use case.

* Tech
Why Clojure? It's a modern, dynamically typed language that can gradually be hardened with robust types and tests. The language is smaller, more self-consistent, and more predictable syntactically than languages like Ruby or JavaScript, and allows the user to easily make their own APIs.

Clojure isn't perfect; the eventual objective is to make the best language for me. For now, though, it's a well-tested, flexible starting point.

