#+TITLE: jacob.chvatal.com

#+BEGIN_EXPORT html
<div id="wcb" class="carbonbadge wcb-d"></div>
<script src="https://unpkg.com/website-carbon-badges@1.1.3/b.min.js" defer></script>
#+END_EXPORT

This is the index of my personal website, found [[https://jacob.chvatal.com][here]].
It's designed to be minimal, providing a brief overview of who I am as well as a variety of links to other services with no JavaScript involved.
No frameworks, no nonsense. Why load several megabytes of data if I only need ~3 kb for something that looks good and conveys all of the right information?

100% score on the [[https://www.foo.software/lighthouse][Lighthouse audit]].

* Goals
- completely optimize a site: display only what i feel is necessary
- shoot for the less than 10 packet goal, showing off rendering and loading tricks
  to prevent blocking actions and documenting these decisions
- custom static site generation from other sources
- research into 'minimal tech' and keeping it simple

* Running
This website locally renders its sources through a Clojure script. ``` lein run > index.html ``` regenerates the home page from a source configuration.

