#+TITLE: jake.isnt.online

This is the index of my personal website found [[https://jake.isnt.online][here]].
It can be thought of as a projection of my wiki and github repos!
100% score on the [[https://www.foo.software/lighthouse][Lighthouse audit]].

* Goals
- Personal landing page with links
- No external resources loaded
- SEO Optimized
- Ten packets (to load instantly)

* Running
To render the website, use `clojure`:
#+BEGIN_SRC sh
clj -X main/-main
#+END_SRC

Why clojure? It's a modern, dynamically typed language that can gradually be hardened with robust types and tests. The language is smaller, more self-consistent, and more predictable syntactically than languages like Ruby or JavaScript, and allows the user to easily make their own APIs.

Clojure isn't perfect; the eventual objective is to make the best language for me. For now, though, it's a well-tested, flexible starting point.

* Deployment
For github pages rendering reasons, the folder that deploys the site must be named `/docs`. Land the static files you'd like to bundle at appropriate paths on that folder.
