#+TITLE: jake.isnt.online

This is the index of my personal website found [[https://jake.isnt.online][here]].
It can be thought of as a projection of my wiki and github repos!
100% score on the [[https://www.foo.software/lighthouse][Lighthouse audit]].

* Goals
- Personal landing page with links
- No external resources loaded
- SEO Optimized
- Ten packets (to load instantly)

* Running
To render the website, use `sbcl` or something:
#+BEGIN_SRC sh
sbcl
#+END_SRC

This website is written in common lisp because common lisp is a good programming language.
* Deployment
For github pages rendering reasons, the folder that deploys the site must be named `/docs`.
* TODO
- Fix spacing on newlines; double newline ++ should insert a break, but single newline should not distance them. not sure how to represent this. make it look like org mode itself!
- fix id links and file links. i care a lot more about file links than i do about id links, but they should both work.
- figure out some way to show what subdirs we have on the website's home pag
