#+TITLE: Todo
* DONE move css to git submodule
CLOSED: [2020-08-04 Tue 19:33]
css should be shared across all sites with the same design langauge
* DONE add a /now page
CLOSED: [2020-08-04 Tue 19:33]
:PROPERTIES:
:ID:       5e2d1073-bfe9-4087-b440-f6eb403e2020
:END:
maybe this should go on the wiki or a blog or something
this should be a quick org mode file that can be easily linked to
to provide an overview of what i am currently doing and link to other things
do i even need/want to expose this?
* TODO figure out how to add a website image that will show as a preview
:PROPERTIES:
:ID:       69f287ad-15f6-4cd7-8123-aaaa8216a0a8
:END:
interested in doing this for linkedin and maybe messaging services or other sites
* TODO add pgp key
* TODO improve css for /now page
currently it looks good but kind of boring
* TODO enable links on /now page
currently links are not rendered as part of the orgparse library
when they are, make sure that they're rendered in the jinja template
* TODO Git push on save for README
i want it to be as seamless as possible!
* TODO consider changing site style and fusing /now with main page
thats kind of the purpose my main page serves anyways?
why have the same information in multiple places?
* TODO parse and add text that is not in list form
i may want to explain some of my decisions!
